services:
  - type: web
    name: memolink-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /health
